import type { Product } from "@/types/product";

export type StoreCategory = {
  id: string;
  name: string;
  href: string;
  imageSrc: string;
};

export type StoreCollection = {
  id: string;
  name: string;
  description: string;
  href: string;
  imageSrc: string;
};

export const storeCategories: StoreCategory[] = [
  {
    id: "cadernos",
    name: "Cadernos",
    href: "/produtos?categoria=cadernos",
    imageSrc: "/images/category-1.svg",
  },
  {
    id: "planner",
    name: "Planners",
    href: "/produtos?categoria=planner",
    imageSrc: "/images/category-2.svg",
  },
  {
    id: "canetas",
    name: "Escrita",
    href: "/produtos?categoria=canetas",
    imageSrc: "/images/category-3.svg",
  },
  {
    id: "presentes",
    name: "Presentes",
    href: "/produtos?categoria=presentes",
    imageSrc: "/images/manifesto-gift.svg",
  },
  {
    id: "adesivos",
    name: "Adesivos",
    href: "/produtos?categoria=adesivos",
    imageSrc: "/images/product-card-placeholder.svg",
  },
  {
    id: "kits",
    name: "Kits",
    href: "/produtos?categoria=kits",
    imageSrc: "/images/manifesto-desk.svg",
  },
];

export const storeCollections: StoreCollection[] = [
  {
    id: "calmaria",
    name: "Colecao Calmaria",
    description: "Linho, papel polen e tons suaves para organizar com leveza.",
    href: "/produtos?categoria=planner",
    imageSrc: "/images/placeholder-hero.svg",
  },
  {
    id: "atelier",
    name: "Colecao Atelier",
    description: "Pecas para escrita diaria com acabamento artesanal.",
    href: "/produtos?categoria=cadernos",
    imageSrc: "/images/hero-detail.svg",
  },
  {
    id: "presentear",
    name: "Colecao Presentear",
    description: "Selecao pronta para entregar afeto em datas especiais.",
    href: "/produtos?categoria=presentes",
    imageSrc: "/images/manifesto-gift.svg",
  },
];

const now = new Date().toISOString();

export const fallbackProducts: Product[] = [
  {
    id: "prd-1",
    name: "Planner Semanal Amanhecer",
    slug: "planner-semanal-amanhecer",
    description: "Planejamento semanal com foco e clareza.",
    price: 8990,
    originalPrice: null,
    categoryId: "planner",
    stockQuantity: 15,
    sku: "PLN-AMN-01",
    rating: 5,
    reviewCount: 12,
    isNew: true,
    isFeatured: true,
    active: true,
    inStock: true,
    images: [{ id: "img-1", imageUrl: "/images/product-1.svg", displayOrder: 1 }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-2",
    name: "Caderno Costura Manual Blush",
    slug: "caderno-costura-manual-blush",
    description: "Encadernacao artesanal com abertura 180 graus.",
    price: 4990,
    originalPrice: null,
    categoryId: "cadernos",
    stockQuantity: 10,
    sku: "CAD-BLS-02",
    rating: 4.9,
    reviewCount: 8,
    isNew: true,
    isFeatured: true,
    active: true,
    inStock: true,
    images: [{ id: "img-2", imageUrl: "/images/product-2.svg", displayOrder: 1 }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-3",
    name: "Kit Escrita Calmaria",
    slug: "kit-escrita-calmaria",
    description: "Caderno, bloco e caneta em curadoria especial.",
    price: 7990,
    originalPrice: 8990,
    categoryId: "kits",
    stockQuantity: 6,
    sku: "KIT-CALM-03",
    rating: 5,
    reviewCount: 16,
    isNew: false,
    isFeatured: true,
    active: true,
    inStock: true,
    images: [{ id: "img-3", imageUrl: "/images/product-3.svg", displayOrder: 1 }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-4",
    name: "Caneta Gel Dourada",
    slug: "caneta-gel-dourada",
    description: "Escrita fina e macia para uso diario.",
    price: 1990,
    originalPrice: null,
    categoryId: "canetas",
    stockQuantity: 22,
    sku: "CAN-GEL-04",
    rating: 4.8,
    reviewCount: 21,
    isNew: true,
    isFeatured: false,
    active: true,
    inStock: true,
    images: [{ id: "img-4", imageUrl: "/images/category-3.svg", displayOrder: 1 }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-5",
    name: "Bloco Notas Botanic",
    slug: "bloco-notas-botanic",
    description: "Bloco para lista rapida com capa ilustrada.",
    price: 3290,
    originalPrice: null,
    categoryId: "cadernos",
    stockQuantity: 14,
    sku: "BLK-BOT-05",
    rating: 4.7,
    reviewCount: 9,
    isNew: false,
    isFeatured: true,
    active: true,
    inStock: true,
    images: [{ id: "img-5", imageUrl: "/images/category-1.svg", displayOrder: 1 }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-6",
    name: "Caixa Presente Afeto",
    slug: "caixa-presente-afeto",
    description: "Composicao pronta para presentear com delicadeza.",
    price: 9890,
    originalPrice: null,
    categoryId: "presentes",
    stockQuantity: 4,
    sku: "PRS-AFT-06",
    rating: 5,
    reviewCount: 13,
    isNew: false,
    isFeatured: true,
    active: true,
    inStock: true,
    images: [{ id: "img-6", imageUrl: "/images/manifesto-gift.svg", displayOrder: 1 }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-7",
    name: "Cartela Adesivos Jardim",
    slug: "cartela-adesivos-jardim",
    description: "Aquarelas florais para decorar agenda e caderno.",
    price: 1490,
    originalPrice: null,
    categoryId: "adesivos",
    stockQuantity: 30,
    sku: "ADS-JAR-07",
    rating: 4.9,
    reviewCount: 18,
    isNew: true,
    isFeatured: false,
    active: true,
    inStock: true,
    images: [{ id: "img-7", imageUrl: "/images/product-card-placeholder.svg", displayOrder: 1 }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-8",
    name: "Planner Mensal Sereno",
    slug: "planner-mensal-sereno",
    description: "Visao mensal objetiva para uma rotina sem ruído.",
    price: 6990,
    originalPrice: null,
    categoryId: "planner",
    stockQuantity: 0,
    sku: "PLN-SER-08",
    rating: 4.8,
    reviewCount: 11,
    isNew: false,
    isFeatured: true,
    active: true,
    inStock: false,
    images: [{ id: "img-8", imageUrl: "/images/category-2.svg", displayOrder: 1 }],
    createdAt: now,
    updatedAt: now,
  },
];